### ISSUE TITLE
NBR Instruction problem

### ISSUE THREAD

**Issue by NullMember** [wd5gnr/1802UNO#1]
Hi
First of all your work is awesome. 
NBR instruction emulated wrong. like NLBR, NBR instruction increment PC + 1. But in emulator it's doing nothing.

**Comment by wd5gnr** [comment]
My testing shows this is fine.

38 7B 00 does not turn on Q
38 00 7B does

This is the same behavior I see on a real 1802. I see you closed the comment before I saw it, so I assume you came to the same conclusion, but just wanted to make sure I didn't miss something.
